language: android
android:
  components:
  - build-tools-23.0.2
  - android-23
  - extra
script: ./gradlew clean assemble test uploadArchives --refresh-dependencies
before_install:
- openssl aes-256-cbc -K $encrypted_4d7c096889b1_key -iv $encrypted_4d7c096889b1_iv
  -in gradle.properties.enc -out gradle.properties -d
